# This is a basic workflow that is manually triggered

name: Test Python App

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Chechout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install depend
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn pydantic-settings pytest httpx

    - name: Run tests
      run: |
        python -m pytest tests/
  
